---
fixtures:
  repositories:
    simpkv: https://github.com/simp/pupmod-simp-simpkv.git
    stdlib: https://github.com/simp/puppetlabs-stdlib.git
    compliance_markup: https://github.com/simp/pupmod-simp-compliance_markup.git
  symlinks:
    simplib: "#{source_dir}"
